### ISSUE TITLE
PlatinumGroupProcessing –  NoSuchFieldError: ChloroplatinicAcid

### ISSUE THREAD

**Issue by tcardlab** [GregTechCEu/gregicality-science#15]
[PlatinumGroupProcessing](https://github.com/GregTechCEu/gregicality-science/blob/6a41bd31f9b9e218f79d019b58be598fd7e980cd/src/main/java/gregicality/science/loaders/recipe/chain/PlatinumGroupProcessing.java#L12) expects ChloroplatinicAcid at lines [145](https://github.com/GregTechCEu/gregicality-science/blob/6a41bd31f9b9e218f79d019b58be598fd7e980cd/src/main/java/gregicality/science/loaders/recipe/chain/PlatinumGroupProcessing.java#L145) and [151](https://github.com/GregTechCEu/gregicality-science/blob/6a41bd31f9b9e218f79d019b58be598fd7e980cd/src/main/java/gregicality/science/loaders/recipe/chain/PlatinumGroupProcessing.java#L151).
However, it is not contained, defined, nor exported from [GCYSMaterials](https://github.com/GregTechCEu/gregicality-science/blob/master/src/main/java/gregicality/science/api/unification/materials/GCYSMaterials.java) or anywhere else afaik.

-------

<summary>

```
java.lang.NoSuchFieldError: ChloroplatinicAcid
	at gregicality.science.loaders.recipe.chain.PlatinumGroupProcessing.platinumProcess(PlatinumGroupProcessing.java:144)
	at gregicality.science.loaders.recipe.chain.PlatinumGroupProcessing.init(PlatinumGroupProcessing.java:29)
	at gregicality.science.loaders.recipe.GCYSRecipeLoader.initChains(GCYSRecipeLoader.java:26)
	at gregicality.science.loaders.recipe.GCYSRecipeLoader.init(GCYSRecipeLoader.java:12)
```

<details>

```
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 947329672 bytes (903 MB) / 1907884032 bytes (1819 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -Xmx8192m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version           | Source                                        | Signature                                |
	|:----- |:--------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp             | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML             | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge           | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | codechickenlib  | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | crafttweaker    | 4.1.20            | CraftTweaker2-1.12-4.1.20.675.jar             | None                                     |
	| LCH   | ctgui           | 1.0.0             | CraftTweaker2-1.12-4.1.20.675.jar             | None                                     |
	| LCH   | jei             | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LCH   | crafttweakerjei | 2.0.3             | CraftTweaker2-1.12-4.1.20.675.jar             | None                                     |
	| LCH   | ctm             | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCH   | gregtech        | 2.3.1-beta        | gregtech-1.12.2-2.3.1-beta.jar                | None                                     |
	| LCH   | gcym            | 1.1.2             | GregicalityMultiblocks-1.12.2-1.1.2.jar       | None                                     |
	| LCH   | gcys            | 1.0               | GregicalityScience-1.12.2-1.0.jar             | None                                     |
	| LCH   | theoneprobe     | 1.4.28            | theoneprobe-1.12-1.4.28.jar                   | None                                     |
```
</details>
</summary>

Edit: Ah, I see the most recent [commit on master](https://github.com/GregTechCEu/gregicality-science/commit/6a41bd31f9b9e218f79d019b58be598fd7e980cd#diff-bbf9636aaef27f74e57dc683fb2bcf9842e8ef007430d33a31416a87439cc35e) replaced it with PotassiumHydroxide.

**Comment by TechLord22** [comment]
The current master branch from now forwards requires a specific version of CEu with features from multiple experimental branches not yet released. You will have to wait for all of the changes necessary to be released before GCYS will work outside the development environment.

**Comment by tcardlab** [comment]
Just to clarify, by "not yet released", do you mean not released on forge/modrinth or not released on github?

**Comment by TechLord22** [comment]
It is not on curseforge, but the source code is technically there on github. It uses a CEu jar rebased across multiple experimental and WIP branches.
